services:
  gwan-admin-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gwan-admin-site
    environment:
      - VITE_API_URL=https://bff.gwan.com.br/api
      - VITE_APP_NAME=GWAN Admin
      - VITE_APP_VERSION=2.0.0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gwan-admin-site.rule=Host(`admin.gwan.com.br`)"
      - "traefik.http.routers.gwan-admin-site.entrypoints=websecure"
      - "traefik.http.routers.gwan-admin-site.tls.certresolver=letsencrypt"
      - "traefik.http.services.gwan-admin-site.loadbalancer.server.port=3000"
    restart: always
    networks:
      - gwan

networks:
  gwan:
    external: true 